### PR TITLE
Remove no logging

### PR DESCRIPTION
**Pull request by SabhyaC26**
Fixes #

Changes proposed in this pull request:

- remove all instances of "--no-logging" from overview.md

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/allenai/tango/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/allenai/tango/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [x] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

## After submitting

- [ ] All GitHub Actions jobs for my pull request have passed.

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
LGTM!

**Review by dirkgr — APPROVED** [review]
@SabhyaC26, feel free to press that merge button :-)

**Comment by SabhyaC26** [comment]
> @SabhyaC26, feel free to press that merge button :-)
Yay! However, I don't have the necessary permissions yet to merge!

**Comment by epwalsh** [comment]
@SabhyaC26 how about now?

**Comment by SabhyaC26** [comment]
@epwalsh still can't, says merging is blocked

**Comment by epwalsh** [comment]
Ugh, okay how about now?

**Comment by SabhyaC26** [comment]
Yes, works, merging and closing

**Pull request merged**
