### PR TITLE
Rjsonnet

### PR DESCRIPTION
**Pull request by dirkgr**
This parses much faster than jsonnet.

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
Nice!

**Comment by dirkgr** [comment]
I don't think this is going to work. Those test failures are genuine errors in the Rust code. I'm not going down that rabbit hole.

**Comment by epwalsh** [comment]
Oddly "tests/common/params_test.py::TestParams::test_env_var_substitution" passes locally.

**Comment by epwalsh** [comment]
I'd like to look into the issue more once I get a chance, so let's keep this open. I think it's still promising.

**Comment by epwalsh** [comment]
I was able to reproduce the error outside of Tango. Opened an issue here: https://github.com/messense/rjsonnet-py/issues/6

**Review by dirkgr — COMMENTED** [review]
Approve!

**Pull request merged**
