### PR TITLE
refactor: move packaging information to `pyproject.toml`

### PR DESCRIPTION
**Pull request by SauravMaheshkar**
Follows the work done in the [**allenai/python-package-template**](https://github.com/allenai/python-package-template).

* https://github.com/allenai/python-package-template/pull/99
* https://github.com/allenai/python-package-template/pull/97
* https://github.com/allenai/python-package-template/pull/96

Request for Review: @epwalsh

### CODE REVIEW

**Review by epwalsh — CHANGES_REQUESTED** [review]
Hey @SauravMaheshkar, thanks for this! Looks like there's a couple more things that need to be updated:
- the symlink `docs/source/CONTRIBUTING.md` needs to be updated to point to `../../.github/CONTRIBUTING.md`
- `Dockerfile` needs to be updated to install from `pyproject.toml` instead of `requirements.txt`.
- `pytest-cov`, `coverage` and `codecov` can be removed from the dev dependencies

**Comment by SauravMaheshkar** [comment]
Addressed in f7c65472e74dd7937e2a9bcd5189a78f1a024065

**Comment by epwalsh** [comment]
I can't get `pip install -e .[dev,all]` to work with the latest release of `pip` ☹️ 
It doesn't pick up on the self-reference and tries to install `ai2-tango` from the latest release on PyPI.

**Comment by epwalsh** [comment]
Well.. apparently it worked in CI?

**Comment by epwalsh** [comment]
Turns out my issues were because `tensorflow-cpu` isn't available for my computer (M1 Mac) I guess

**Pull request merged**
