### PR TITLE
Adds an option to massage kwargs before they go to the Step's `run()`…

### PR DESCRIPTION
**Pull request by dirkgr**

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]

**Comment by dirkgr** [comment]
@epwalsh, I added another fix. Can you give it another look?

**Comment by epwalsh** [comment]
@dirkgr am I missing a commit? I this changelog update https://github.com/allenai/tango/pull/211/commits/374f28e9710769fdd9704679665e9746fe59cfc7, but I don't see changes that actually address that.

**Comment by dirkgr** [comment]
🤦🏻

**Review by epwalsh — APPROVED** [review]
✅

**Pull request merged**
