### PR TITLE
rename settings.json -> .workspace-metadata.json

### PR DESCRIPTION
**Pull request by epwalsh**

### CODE REVIEW

**Review by dirkgr — COMMENTED** [review]
Do we really need all that stuff? `from_params()`, `to_params()`, data classes, `ClassVar` ... all we're doing is storing an integer. What does it buy us?

**Comment by epwalsh** [comment]
> Do we really need all that stuff? from_params(), to_params(), data classes, ClassVar ... all we're doing is storing an integer. What does it buy us?

You said yourself "I thought maybe we'd put other settings in there at some point." This makes it easier to add more fields in the future.

**Comment by dirkgr** [comment]
Let's make it complicated when we have enough things to store to make it worth it.

**Comment by epwalsh** [comment]
The other reason I did it that way was to be consistent with all of the other `*Metadata` classes. Seems odd to make a special case here for `WorkspaceMetadata` just because we don't have more fields *yet*.

**Comment by epwalsh** [comment]
It's not exactly what `FromParams` was designed for, but IMO the other best alternative for these `*Metadata` classes involves adding another dependency like `pydantic` or `attrs`.

**Pull request closed without merging**
