### PR TITLE
Log from `BeakerStepLock` at WARNING level

### PR DESCRIPTION
**Pull request by epwalsh**

### CODE REVIEW

**Review by dirkgr — APPROVED** [review]
This is good, but tests don't pass.

**Comment by dirkgr** [comment]
Should this be printed to the click logger? Do we still have that?

**Comment by epwalsh** [comment]
> Should this be printed to the click logger? Do we still have that?

We still have that (it's the `cli_logger` now), but the downside would be that those messages wouldn't show up when using Tango programmatically unless the our `initialize_logging()` function was called with `enable_cli_logs=True`.

**Comment by dirkgr** [comment]
`WARNING` is our cheap way of getting both at the same time? I think it's OK in this case.

**Comment by epwalsh** [comment]
> WARNING is our cheap way of getting both at the same time? I think it's OK in this case.

Right

**Comment by epwalsh** [comment]
> This is good, but tests don't pass.

Looks like Beaker is still broken 🙂

**Pull request merged**
